import { Button, Center, Container, Text } from "@mantine/core";
import router from "next/router";
import { useState } from "react";
import OtpInput from "react-otp-input";
import handleError from "../../../src/helpers/handleError";
import handleSuccess from "../../../src/helpers/handleSuccess";
import Server from "../../../src/Server";

const EnterCodePage = () => {
  const [code, setCode] = useState("");

  const { email, password, rememberMe } = router.query;

  const [verifying, setVerifying] = useState(false);

  const handleVerifyCode = (e) => {
    e.preventDefault();

    setVerifying(true);
    Server.post("/auth/sign-in/two", {
      email,
      password,
      code,
      rememberMe: eval(rememberMe),
    })
      .then((res) => {
        localStorage.setItem("accessToken", res.data.token);
        handleSuccess(res);
        setVerifying(false);

        setTimeout(() => {
          router.push("/");
        }, 1500);
      })
      .catch((error) => {
        handleError(error, "Verification Error");
        setVerifying(false);
      });
  };

  return (
    <Center
      component={"form"}
      style={{
        width: "100%",
        height: "100vh",
      }}
      onSubmit={handleVerifyCode}
    >
      <Container>
        <Container
          style={{
            maxWidth: "464px",
          }}
        >
          <Text align={"center"}>
            Please enter the One Time Password (OTP) generated by your Microsoft
            Authenticator App.
          </Text>
        </Container>

        <Container
          my={"sm"}
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <OtpInput
            value={code}
            numInputs={6}
            separator={<span>&nbsp;-&nbsp;</span>}
            inputStyle={{
              width: "30px",
              padding: "8px",
            }}
            onChange={(val) => {
              setCode(val);
            }}
          />
        </Container>

        <Container>
          <Button
            type={"submit"}
            loading={verifying}
            style={{
              display: "flex",
            }}
            mx={"auto"}
          >
            Verify
          </Button>
        </Container>
      </Container>
    </Center>
  );
};

export default EnterCodePage;
